export const CHAT_MAX_LENGTH = 1000
export const COMMENT_MAX_LENGTH = 300
export const DIR_NAME_MAX_LENGTH = 32
export const FILE_NAME_MAX_LENGTH = 40
export const USER_NAME_LENGTH_MAX = 20

export const [ALARM_STATUS_NEW, ALARM_STATUS_OLD] = [0, 1]

export const [ALARM_TYPE_FILE_COMMENT, ALARM_TYPE_COMMENT_REPLY, ALARM_TYPE_TAG_REPLY] = [0, 1, 2]

export const [CHAT_ROOM_STATUS_INACTIVE, CHAT_ROOM_STATUS_ACTIVE] = [0, 1]
